config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'recipes#index'
  resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '1人分' },
    { id: 2, name: '2人分' },
    { id: 3, name: '3人分' },
    { id: 4, name: '4人分' }
  ]

  include ActiveHash::Associations
  has_many :recipes
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :person

  validate :image_content_type, :image_size, if: Proc.new {|recipe| recipe.image.present?}
  
  def image_content_type
    if !image.content_type.in?(%('image/png', 'image/jpg', 'image/jpeg'))
      errors.add(:image, "にはjpegまたはpngファイルを添付してください")
    end
  end

  def image_size
    if image.blob.byte_size > 5.megabytes
      errors.add(:image, "は5MB以内にしてください")
    end
  end

  with_options presence: true do
    validates :image
    validates :name
    validates :person_id
    validates :material
    validates :step1
  end

  
  
  
  # 人数分の選択が「--」の時は保存できないようにする
  validates :person_id, numericality: { other_than: 0 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes

  validates :nickname, presence: true
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates :password, format: { with: PASSWORD_REGEX }

  def self.guest
    find_or_create_by(email: 'guest@sample.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.nickname = "guest"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :basic_auth //Basic認証
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  # def basic_auth //Basic認証
  #   authenticate_or_request_with_http_basic do |username, password|
  #     username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
  #   end
  # end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @recipes = Recipe.all.order('created_at DESC')
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.valid?
      @recipe.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
    redirect_to root_path if current_user.id != @recipe.user_id
  end

  def update
    @recipe.update(recipe_params)
    if @recipe.valid?
      redirect_to recipe_path
    else
      render :edit
    end
  end

  def destroy
    if current_user.id == @recipe.user_id
      @recipe.destroy
      if @recipe.destroy
        redirect_to root_path
      else
        render :show
      end
    else
      render :show
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:image, :name, :person_id, :material, :step1, :step2, :step3,
                                   :step4).merge(user_id: current_user.id)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>COOK TIMER</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/edit.html.erb
<%# cssはレシピ投稿のものを併用
app/assets/stylesheets/recipes/new.css %>

<%= render "shared/header" %>


<body class="post-recipe">

  <%= form_with model: @recipe, local: true do |f| %>

    <%# エラー発生時にメッセージを表示 %>
    <%= render 'shared/error_messages', model: f.object %>
    <%# //エラー発生時にメッセージを表示%>


    <div class="new-recipe">
      <h2>レシピの情報を入力</h2>

      <%# 写真 %>
      <div class="image">
        <b>料理の写真<span class="indispensable">必須</span></b>
        <div class="click-upload">
          <p>クリックしてファイルをアップロード</p>
          <%= f.file_field :image %>
        </div>
      </div>
      <%# /写真 %>

      <%# 料理名 %>
      <div class="name">
        <b>料理名<span class="indispensable">必須</span></b>
        <%= f.text_area :name, class:"form", id:"recipe-name", placeholder:"料理名（必須 40文字まで)", maxlength:"40" %>
      </div>
      <%# /料理名 %>

      <%# 人数分 %>
      <a class="person_id">
        <b>人数分<span class="indispensable">必須</span></b>
        <%= f.collection_select(:person_id, Person.all, :id, :name, {}, {class:"select-box", id:"recipe-person"}) %>
      </a>
      <%# /何人分？ %>

      <%# 材料 %>
      <div class="material">
        <b>材料<span class="indispensable">必須</span></b>
        <%= f.text_area :material, class:"form", id:"recipe-info", placeholder:"材料\n 例）豚肉:350g\n\n調味料\n 例）砂糖:大さじ1" ,rows:"7" ,maxlength:"100" %>
      </div>
      <%# /材料 %>

      <b>作り方</b>
      <div class="step">
        <%# STEP1 %>
        <div class="step1">
          <b>STEP1<span class="indispensable">必須</span></b>
          <%= f.text_area :step1, class:"form", id:"recipe-info", placeholder:"手順1を入力" ,rows:"5" ,maxlength:"100" %>
        </div>
        <%# /STEP1 %>

        <%# STEP2 %>
        <div class="step2">
          <b>STEP2</b>
          <%= f.text_area :step2, class:"form", id:"recipe-info", placeholder:"手順2を入力" ,rows:"5" ,maxlength:"100" %>
        </div>
        <%# /STEP2 %>

        <%# STEP3 %>
        <div class="step3">
          <b>STEP3</b>
          <%= f.text_area :step3, class:"form", id:"recipe-info", placeholder:"手順3を入力" ,rows:"5" ,maxlength:"100" %>
        </div>
        <%# /STEP3 %>

        <%# STEP4 %>
        <div class="step4">
          <b>STEP4</b>
          <%= f.text_area :step4, class:"form", id:"recipe-info", placeholder:"手順4を入力" ,rows:"5" ,maxlength:"100" %>
        </div>
      </div>
      
    </div>

    <%# 変更ボタンと「もどる」ボタン %>
    <div class="btn">
        <%= f.submit "変更する" ,class:"post-btn" %>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>

  <% end %>
</body>


<%= render "shared/footer" %>

app/views/recipes/index.html.erb
<%= render "shared/header" %>


<body>

  <figure class="hero">
    <%= image_tag "hero-img.jpg", class: "hero-img" %>
  </figure>

  <h1>キッチンタイマーがあるレシピアプリ</h1>

  <p>
    <%= image_tag "タイマーアイコン.svg" %>
    <%= image_tag "プラスマークアイコン 6.svg", class: "plus-icon" %>
    <%= image_tag "コックアイコン.svg" %>
    <br>いちいちキッチンタイマーを押しに行く…
    <br>わざわざタイマーアプリを開く…
    <br>そんな”めんどくさい"を
    <br>解消しました
    <%# レシピ投稿ボタン %>
    <% if user_signed_in? %> <%# ログインユーザーのみ表示 %>
      <br><%= link_to "レシピを投稿", new_recipe_path, class: "post" %>
    <% end %>
    <%# レシピ投稿ボタン %>
  </p>

  <recipe-lists>

    <h2>新着レシピ</h2>

    <% @recipes.each do |recipe| %>
      <div class="list">
        <%= link_to recipe_path(recipe.id) do %>
          <div class='recipe-img-content'>
            <%= image_tag recipe.image.variant(resize_to_fill: [300, 200]), class: "recipe-img" if recipe.image.attached? %>
          </div>
          <h3 class='recipe-name'>
            <%= recipe.name %>
          </h3>
        <% end %>
      </div>
    <% end %>

    <%# レシピがない場合のみ表示されるサンプル %>
    <% if @recipes.blank? %>
      <div class='list'>
          <%= image_tag "sample.jpg", class: "recipe-img" %>
          <div class='recipe-info'>
            <h3 class='recipe-name'>
              レシピを投稿してね！
            </h3>
          </div>
      </div>
    <% end %>
    <%# /レシピがない場合のみ表示されるサンプル %>

  </recipe-lists>

</body>


<%= render "shared/footer" %>

app/views/recipes/new.html.erb
<%= render "shared/header" %>


<body class="post-recipe">

  <%= form_with model: @recipe, local: true do |f| %>

    <%# エラー発生時にメッセージを表示 %>
    <%= render 'shared/error_messages', model: f.object %>
    <%# //エラー発生時にメッセージを表示%>


    <div class="new-recipe">
      <h2>レシピの情報を入力</h2>

      <%# 写真 %>
      <div class="image">
        <b>料理の写真<span class="indispensable">必須</span></b>
        <div class="click-upload">
          <p>クリックしてファイルをアップロード</p>
          <%= f.file_field :image %>
        </div>
      </div>
      <%# /写真 %>

      <%# 料理名 %>
      <div class="name">
        <b>料理名<span class="indispensable">必須</span></b>
        <%= f.text_area :name, class:"form", id:"recipe-name", placeholder:"料理名（必須 40文字まで)", maxlength:"40" %>
      </div>
      <%# /料理名 %>

      <%# 人数分 %>
      <a class="person_id">
        <b>人数分<span class="indispensable">必須</span></b>
        <%= f.collection_select(:person_id, Person.all, :id, :name, {}, {class:"select-box", id:"recipe-person"}) %>
      </a>
      <%# /何人分？ %>

      <%# 材料 %>
      <div class="material">
        <b>材料<span class="indispensable">必須</span></b>
        <%= f.text_area :material, class:"form", id:"recipe-info", placeholder:"材料\n 例）豚肉:350g\n\n調味料\n 例）砂糖:大さじ1" ,rows:"7" ,maxlength:"100" %>
      </div>
      <%# /材料 %>

      <b>作り方</b>
      <div class="step">
        <%# STEP1 %>
        <div class="step1">
          <b>STEP1<span class="indispensable">必須</span></b>
          <%= f.text_area :step1, class:"form", id:"recipe-info", placeholder:"手順1を入力" ,rows:"5" ,maxlength:"100" %>
        </div>
        <%# /STEP1 %>

        <%# STEP2 %>
        <div class="step2">
          <b>STEP2</b>
          <%= f.text_area :step2, class:"form", id:"recipe-info", placeholder:"手順2を入力" ,rows:"5" ,maxlength:"100" %>
        </div>
        <%# /STEP2 %>

        <%# STEP3 %>
        <div class="step3">
          <b>STEP3</b>
          <%= f.text_area :step3, class:"form", id:"recipe-info", placeholder:"手順3を入力" ,rows:"5" ,maxlength:"100" %>
        </div>
        <%# /STEP3 %>

        <%# STEP4 %>
        <div class="step4">
          <b>STEP4</b>
          <%= f.text_area :step4, class:"form", id:"recipe-info", placeholder:"手順4を入力" ,rows:"5" ,maxlength:"100" %>
        </div>
      </div>

    </div>

    <%# 投稿ボタンと「もどる」ボタン %>
    <div class="btn">
        <%= f.submit "投稿する" ,class:"post-btn" %>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>

  <% end %>
</body>


<%= render "shared/footer" %>

app/views/recipes/show.html.erb
<%= render "shared/header" %>


<body class="show-recipe">

  <%# レシピの概要 %>
  <div class="recipe">
    <figure class="image">
      <%= image_tag @recipe.image ,class:"recipe-img" %>
    </figure>
    <div class="name">
      <%= @recipe.name %>
    </div>
    <a class="person_id">
      <b>材料(<%= @recipe.person.name %>)</b>
    </a>
    <a class="material">
      <%= @recipe.material %>
    </a>

    <b>作り方</b>
    <div class="step">
      <a class="step1">
        <b>STEP1</b>
        <br><%= @recipe.step1 %>
      </a>
      <a class="step2">
        <b>STEP2</b>
        <br><%= @recipe.step2 %>
      </a>
      <a class="step3">
        <b>STEP3</b>
        <br><%= @recipe.step3 %>
      </a>
      <a class="step4">
        <b>STEP4</b>
        <br><%= @recipe.step4 %>
      </a>
    </div>
  </div>

  <div class="sub">
    <%# タイマー %>
    <%= render "shared/timer" %>

    <%# 編集ボタンと削除ボタン%>
    <div class="btn">
      <% if user_signed_in? %>
        <% if current_user.id == @recipe.user_id %>
          <%= link_to 'レシピを編集', edit_recipe_path(@recipe.id), method: :get, class: 'edit-btn' %>
          <%= link_to 'レシピを削除', recipe_path(@recipe.id), method: :delete, class: 'destroy-btn' %>
        <% end %>
      <% end %>
    </div>
  </div>

</body>


<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
      <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>© COOKTIMER 2021.</footer>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header>
  <%= link_to "COOK TIMER", "/" %>
</header>

<nav>
  <%# ログインの有無で表示が変わるよう分岐 %>
  <% if user_signed_in? %>
    <ul class="signed-in">
      <li><%= current_user.nickname %>さん、こんにちは！</li>
      <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
      <%# <li><%= link_to "レシピを投稿", new_recipe_path, class: "post" %></li>
    </ul>
  <% else %>
    <ul class="signed-up">
      <li><%= link_to "ゲストログイン(閲覧用)", users_guest_sign_in_path, method: :post %></li>
      <li><%= link_to "ログイン", new_user_session_path %></li>
      <li><%= link_to "新規登録", new_user_registration_path %></li>
    </ul>
  <%# ログインの有無で表示が変わるよう分岐 %>
  <% end %>
</nav>

app/views/shared/_timer.html.erb
<div class="timer-container">
  <div class="timer" id="timer">00:00.000</div>
  <div class="controls">
    <div id="min">分</div>
    <div id="sec">秒</div>
    <div id="reset">リセット</div>
    <div id="start">スタート</div>
  </div>
</div>

<%= audio_tag 'alarm.mp3', id: "alarm-sound" %>

<script language="javascript" type="text/javascript">

  (function() {
    'use strict';

    //定義
    var timer = document.getElementById('timer');
    var min = document.getElementById('min');
    var sec = document.getElementById('sec');
    var reset = document.getElementById('reset');
    var start = document.getElementById('start');

    var alarm = document.getElementById('alarm-sound');

    //この下で定義しているものを使ってカウントダウンする
    var startTime;
    var timeLeft;
    var timeToCountDown = 0;
    var timerId;
    var isRunning = false;

    //現在時刻を代入し、表示の仕方を設定
    function updateTimer(t) {
      var d = new Date(t);  //現在時刻
      var m = d.getMinutes();
      var s = d.getSeconds();
      var ms = d.getMilliseconds();
      m = ('0' + m).slice(-2);  //「０」が表示される桁を設定
      s = ('0' + s).slice(-2);
      ms = ('00' + ms).slice(-3);
      timer.textContent = m + ':' + s + '.' + ms;  //表示される文字列を設定
    }

    //カウンドダウン処理
    function countDown() {
      timerId = setTimeout(function() {
        // var elapsedTime = Data.now() - startTime;
        // timeLeft = timeToCountDown - elapsedTime;
        timeLeft = timeToCountDown - (Date.now() - startTime);  //現在時刻から開始時間を引いて、さらに終わり時間から引くことで残り時間を算出している
        if (timeLeft < 0) {
          alarm.play();  //カウントダウンが０になるとアラーム音が再生される
          isRunning = false;
          start.textContent = 'スタート';
          clearTimeout(timerId);
          timeLeft = 0;
          timeToCountDown = 0;
          updateTimer(timeLeft);
          return;
        }
        updateTimer(timeLeft);
        countDown();
      }, 10);
    }

    // アラーム音が鳴るのを途中で止める
    reset.addEventListener('click', function() {
      alarm.pause();
    });

    min.addEventListener('click', function() {
      alarm.pause();
    });

    sec.addEventListener('click', function() {
      alarm.pause();
    });

    //スタートとストップの処理
    start.addEventListener('click', function() {
      if (isRunning === false) {
        alarm.load();  //スマホでアラーム音が鳴るよう「スタート」ボタンを押した時点でmp3を読み込む
        isRunning = true;
        start.textContent = 'ストップ';
        startTime = Date.now();
        countDown();
      } else {
        isRunning = false;
        start.textContent = 'スタート';
        timeToCountDown = timeLeft;
        clearTimeout(timerId);
      }
    });

    //分入力の処理
    min.addEventListener('click', function() {
      if (isRunning === true) {
        return;
      }
      timeToCountDown += 60 * 1000;
      if (timeToCountDown >= 60 * 60 * 1000) {
        timeToCountDown = 0;
      }
      updateTimer(timeToCountDown);
    });

    //秒入力の処理
    sec.addEventListener('click', function() {
      if (isRunning === true) {
        return;
      }
      timeToCountDown += 1000;
      if (timeToCountDown >= 60 * 60 * 1000) {
        timeToCountDown = 0;
      }
      updateTimer(timeToCountDown);
    });

    //リセット処理
    reset.addEventListener('click', function() {
      timeToCountDown = 0;
      updateTimer(timeToCountDown);
    });
    
  })();
</script>